# .github/workflows/sql-deploy.yml
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/sql-action@v1
      with:
        server-name: sqlaction-server
        connection-string: Server=tcp:sqlaction-server.database.windows.net,1433;Initial Catalog=GithubAction;Persist Security Info=False;User ID=winmaria;Password=VJ.phool1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        dacpac-package: './Database.dacpac'
